(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var k=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},m=k(this),n="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},r;
if("function"==typeof Object.setPrototypeOf)r=Object.setPrototypeOf;else{var t;a:{var u={a:!0},w={};try{w.__proto__=u;t=w.a;break a}catch(a){}t=!1}r=t?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var x=r,y=function(a,b){a.prototype=n(b.prototype);a.prototype.constructor=a;if(x)x(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,c);f&&Object.defineProperty(a,c,f)}else a[c]=b[c]},z=this||self,A=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};var B=function(a){a=1-a;return 1-a*a*a};var C=/[^\d]+$/,F=function(a,b,c,f){if(!a.hasAttribute(b))return c;a=a.getAttribute(b);isNaN(parseFloat(a))?f=c:(c=parseFloat(a),(a=(a=a.match(C))&&a[0]||null)&&(a=a.trim()),b=c,"%"==a&&(b=Number((c/100*f).toFixed(2))),f=b);return f};var da=function(a,b,c){var f=F(a,"xenter",0,b),e=a.hasAttribute("xmiddle")?F(a,"xmiddle",0,b):void 0,d=F(a,"xexit",0,b),h=F(a,"yenter",0,c),l=a.hasAttribute("ymiddle")?F(a,"ymiddle",0,c):void 0,g=F(a,"yexit",0,c),p=G(a,"opacityenter"),q=G(a,"opacitymiddle"),D=G(a,"opacityexit"),E=a.hasAttribute("fixed"),W=a.getAttribute("assettype")||"",X=a.getAttribute("source")||"",Y=a.getAttribute("easing")||"linear";b=F(a,"width",b,b);c=F(a,"height",c,c);var Z=a.hasAttribute("yawenter")?parseInt(a.getAttribute("yawenter"),
10):void 0,aa=a.hasAttribute("yawmiddle")?parseInt(a.getAttribute("yawmiddle"),10):void 0,ba=a.hasAttribute("yawexit")?parseInt(a.getAttribute("yawexit"),10):void 0,ca=a.getAttribute("exit-url")||void 0,v=[];v.push({opacity:p,x:f,y:h,j:Z});void 0!==e&&void 0!==l&&v.push({opacity:q,x:e,y:l,j:aa});v.push({opacity:D,x:d,y:g,j:ba});return{P:W,f:v,easing:Y,element:a,H:ca,fixed:E,height:c,source:X,width:b}},H=function(a,b,c,f,e,d){e=void 0===e?0:e;d=void 0===d?1:d;if(f<=e)return a;if(f>=d)return b;switch(c){case "ease-in":c=
f*f*f;e*=e*e;d*=d*d;break;case "ease-in-out":c=3*f*f-2*f*f*f;e=3*e*e-2*e*e*e;d=3*d*d-2*d*d*d;break;case "ease-out":c=B(f);e=B(e);d=B(d);break;default:c=f}return 1/(d-e)*(b-a)*(c-e)+a},G=function(a,b){if(!a.hasAttribute(b))return 1;a=a.getAttribute(b);a=parseFloat(a);return isNaN(a)?1:0>a?0:1<a?1:a};var I=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a};var J=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,J);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};A(J,Error);J.prototype.name="CustomError";var K=function(a,b){a=a.split("%s");for(var c="",f=a.length-1,e=0;e<f;e++)c+=a[e]+(e<b.length?b[e]:"%s");J.call(this,c+a[f])};A(K,J);K.prototype.name="AssertionError";var ea=function(a,b,c){if(!a){var f="Assertion failed";if(b){f+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new K(""+f,e||[]);}return a},fa=function(a,b){throw new K("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var N=function(a,b){this.F=a===L&&b||"";this.O=M};N.prototype.A=!0;N.prototype.v=function(){return this.F.toString()};N.prototype.toString=function(){return"SafeUrl{"+this.F+"}"};var ha=function(a){if(a instanceof N&&a.constructor===N&&a.O===M)return a.F;var b=typeof a;fa("expected object of type SafeUrl, got '"+a+"' of type "+("object"!=b?b:a?Array.isArray(a)?"array":b:"null"));return"type_error:SafeUrl"},ia=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,M={},L={};var O=function(){this.D=""};O.prototype.A=!0;O.prototype.v=function(){return this.D};O.prototype.toString=function(){return"SafeStyle{"+this.D+"}"};O.prototype.B=function(a){this.D=a};(new O).B("");var P=function(){this.C=""};P.prototype.A=!0;P.prototype.v=function(){return this.C};P.prototype.toString=function(){return"SafeStyleSheet{"+this.C+"}"};P.prototype.B=function(a){this.C=a};(new P).B("");var Q=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},ja=function(a){if(Q(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&Q(a))return a;return null};var R=function(a,b,c){c=void 0===c?null:c;var f=document.createEvent("CustomEvent");f.initCustomEvent(a,!0,!0,c);b.dispatchEvent(f);return f};var ka=[],S=function(){var a=HTMLElement.call(this)||this;a.s=[];a.L=null;a.l=null;a.i=[0,1];a.h=[];a.u=a.R.bind(a);a.G=!1;a.M=!1;a.N=a.U.bind(a);a.K=0;a.J=a.T.bind(a);a.I=a.S.bind(a);a.m=null;return a};y(S,HTMLElement);
S.prototype.connectedCallback=function(){this.ownerDocument.addEventListener("hostpagescroll",this.N);window.Enabler&&(Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.J),Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.I));if(!this.gwdIsLoaded()){var a=ja(this);a?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad()}};
S.prototype.disconnectedCallback=function(){this.ownerDocument.removeEventListener("hostpagescroll",this.N);window.Enabler&&(Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.J),Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.I));this.removeEventListener("ready",this.u,!1)};
S.prototype.gwdLoad=function(){if(!this.gwdIsLoaded()){this.h.length=0;this.initializeParallax(!0);for(var a=this.h.length-1;0<=a;a--)this.h[a].gwdLoad();this.h=this.h.filter(function(b){return!b.gwdIsLoaded()});0==this.h.length?T(this):this.addEventListener("ready",this.u,!1)}};S.prototype.gwdIsLoaded=function(){return this.G&&0==this.h.length};S.prototype.R=function(a){a=this.h.indexOf(a.target);0<=a&&(this.h.splice(a,1),0==this.h.length&&(T(this),this.removeEventListener("ready",this.u,!1)))};
var T=function(a){a.M||R("ready",a);a.M=!0;a.m&&(U(a,a.m.creativeFramePercentY,a.m.windowHeight+a.l),a.m=null)};
S.prototype.initializeParallax=function(a){var b=this;this.style.overflow="hidden";this.s.length=0;this.L=this.clientWidth;this.l=this.clientHeight;this.i=la(this);for(var c=this.ownerDocument,f={},e=0;e<this.children.length;f={o:f.o},e++)if(!this.children[e].hasAttribute("data-gwd-csd-ghost-id")){var d=da(this.children[e],this.L,this.l);this.s.push(d);d.element.style.position="absolute";d.element.style.left="0px";d.element.style.top="0px";d.element.style.width=d.width+"px";d.element.style.height=
d.height+"px";d.element.style.transform="translate("+d.f[0].x+"px, "+d.f[0].y+"px)";d.element.style.opacity=d.f[0].opacity+"";void 0!=d.f[0].j&&d.element.setTargetYaw(d.f[0].j);if(a){if("image"==d.P&&d.source){for(;d.element.firstChild;)d.element.removeChild(d.element.firstChild);var h=c.createElement("gwd-image");h.style.width="100%";h.style.height="100%";h.setAttribute("source",d.source);this.h.push(h);d.element.appendChild(h)}else d.element.gwdLoad&&this.h.push(d.element);d.H&&(f.o=d.H,d.element.addEventListener("click",
function(l){return function(){if(!R("layerclickexit",b,{url:l.o}).detail.handled){var g=l.o;g instanceof N||g instanceof N||(g="object"==typeof g&&g.A?g.v():String(g),ea(ia.test(g),"%s does not match the safe URL pattern",g)||(g="about:invalid#zClosurez"),g=new N(L,g));z.open(ha(g),"",void 0,void 0)}}}(f)))}}this.G=!0};S.prototype.U=function(a){a=a.detail;this.K=a.creativeFramePercentY;this.gwdIsLoaded()?U(this,a.creativeFramePercentY,a.windowHeight+this.l):this.m=a};
var U=function(a,b,c){for(var f=0;f<a.s.length;f++){var e=a.s[f],d=void 0,h=void 0;d=e.f.length-1;var l=a.i[0],g=a.i[a.i.length-1],p=e.f[0],q=e.f[e.f.length-1];if(e.f.length===a.i.length)for(h=0;h<d;h++)if(a.i[h]<=b&&b<=a.i[h+1]){l=a.i[h];g=a.i[h+1];p=e.f[h];q=e.f[h+1];break}e.fixed?(d=e.f[0].x,h=e.f[0].y+b*c):(d=H(p.x,q.x,e.easing,b,l,g),h=H(p.y,q.y,e.easing,b,l,g));var D=H(p.opacity,q.opacity,e.easing,b,l,g);e.element.style.transform="translate("+d+"px, "+h+"px)";e.element.style.opacity=D+"";e.f.some(function(E){return void 0===
E.j})||e.element.setTargetYaw(Math.round(H(p.j,q.j,e.easing,b,l,g)))}R("parallaxscrolled",a,{yscroll:b})},la=function(a){var b=I(a,"start",0),c=I(a,"end",1);if(0>b||1<b||0>c||1<c||b>=c)b=0,c=1;a=I(a,"middle",-1);return a>=b&&a<=c?[b,a,c]:[b,c]};S.prototype.T=function(){var a=this;setTimeout(function(){a.initializeParallax(!1);U(a,1,window.innerHeight+a.l)},0)};S.prototype.S=function(){var a=this;setTimeout(function(){a.initializeParallax(!1);U(a,a.K,window.innerHeight+a.l)},0)};
m.Object.defineProperties(S,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ka}}});var V=function(){return S.call(this)||this};y(V,S);customElements.define("gwd-parallax",V);}).call(this);
